name: test_workflow
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: copy files
      run: |
        mkdir rename
        ls
        pwd
    - name: Just checking
      run: |
         ls
         pwd
         cd rename
         touch new.txt
         ls -al
         pwd
         
